apiVersion: v1
kind: Service
metadata:
  name: zettelkasten
spec:
  ports:
  - port: 8080
    name: tcp
  - port: 8000
    name: web
  selector:
    app: zettelkasten
---
apiVersion: v1
kind: Service
metadata:
  name: zettelkasten-headless
spec:
  clusterIP: None
  ports:
  - port: 8080
    name: tcp
  selector:
    app: zettelkasten
