apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zettelkasten
spec:
  serviceName: "zettelkasten"
  replicas: 3
  selector:
    matchLabels:
      app: zettelkasten
  template:
    metadata:
      labels:
        app: zettelkasten
    spec:
      containers:
      - name: db
        image: zettelkasten:latest
        ports:
        - containerPort: 8080
          name: tcp
        - containerPort: 8000
          name: web
        volumeMounts:
        - name: data
          mountPath: /app/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
